export const ROLES = { HR: 'HR', MANAGER: 'MANAGER', EMPLOYEE: 'EMPLOYEE' };
export const APPRAISAL_STATUSES = ['DRAFT','SUBMITTED','REVIEWED','APPROVED'];
export const GOAL_STATUSES = ['DRAFT','ASSIGNED','ACKNOWLEDGED','COMPLETED','APPROVED','REJECTED'];
export const REVIEW_STATUSES = ['DRAFT','SUBMITTED','APPROVED'];
